{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-47609",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-10-02T13:16:26.504456Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:hyperium:tonic:*:*:*:*:*:*:*:*"
            ],
            "vendor": "hyperium",
            "product": "tonic",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "versionType": "custom",
                "lessThanOrEqual": "0.12.2"
              },
              {
                "status": "affected",
                "version": "0",
                "versionType": "custom",
                "lessThanOrEqual": "0.12.3"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-10-02T13:14:25.218Z"
        }
      }
    ],
    "cna": {
      "title": "Remotely exploitable DoS in Tonic `<=v0.12.2`",
      "source": {
        "advisory": "GHSA-4jwc-w2hc-78qv",
        "discovery": "UNKNOWN"
      },
      "metrics": [
        {
          "cvssV4_0": {
            "version": "4.0",
            "baseScore": 6.9,
            "attackVector": "NETWORK",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N/U:Green",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "attackRequirements": "NONE",
            "privilegesRequired": "NONE",
            "subIntegrityImpact": "NONE",
            "vulnIntegrityImpact": "NONE",
            "subAvailabilityImpact": "NONE",
            "vulnAvailabilityImpact": "LOW",
            "subConfidentialityImpact": "NONE",
            "vulnConfidentialityImpact": "NONE"
          }
        }
      ],
      "affected": [
        {
          "vendor": "hyperium",
          "product": "tonic",
          "versions": [
            {
              "status": "affected",
              "version": ">= 0.12.2, < 0.12.3"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/hyperium/tonic/security/advisories/GHSA-4jwc-w2hc-78qv",
          "name": "https://github.com/hyperium/tonic/security/advisories/GHSA-4jwc-w2hc-78qv",
          "tags": [
            "x_refsource_CONFIRM"
          ]
        },
        {
          "url": "https://github.com/hyperium/tonic/issues/1897",
          "name": "https://github.com/hyperium/tonic/issues/1897",
          "tags": [
            "x_refsource_MISC"
          ]
        },
        {
          "url": "https://github.com/hyperium/tonic/commit/a4472a86f3290e60c7c01348b7e6a8164d6e7e48",
          "name": "https://github.com/hyperium/tonic/commit/a4472a86f3290e60c7c01348b7e6a8164d6e7e48",
          "tags": [
            "x_refsource_MISC"
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "Tonic is a native gRPC client & server implementation with async/await support. When using tonic::transport::Server there is a remote DoS attack that can cause the server to exit cleanly on accepting a TCP/TLS stream. This can be triggered by causing the accept call to error out with errors that were not covered correctly causing the accept loop to exit. Upgrading to tonic 0.12.3 and above contains the fix."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-755",
              "description": "CWE-755: Improper Handling of Exceptional Conditions"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2024-10-01T20:13:55.017Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-47609",
    "state": "PUBLISHED",
    "dateUpdated": "2024-11-21T16:56:13.633Z",
    "dateReserved": "2024-09-27T20:37:22.120Z",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "datePublished": "2024-10-01T20:13:55.017Z",
    "assignerShortName": "GitHub_M"
  },
  "dataVersion": "5.1"
}